In [2]:
import pandas as pd
from tabulate import tabulate
import matplotlib.pyplot as plt

## Importing the csv file

In [121]:
original_data=pd.read_csv('Tokyo_Dataset.csv')
data=original_data.copy()

In [122]:
data.shape

(10000, 32)

In [123]:
# checking nulls 
null_counts =data.isnull().sum()
null_counts

Unnamed: 0                 0
hospital_name              0
hospital_id                0
patient_id                 0
doctor_id                  0
Patient_first_name         0
Patient_last_name          0
doctor_name                0
hospital_ward              0
patient_gender             0
patient_race               0
department_referral        0
doctor_specialty           0
patient_assigned_doctor    0
patient_disease            0
discharge_status           0
time_slot                  0
hospital_beds_available    0
occupied_beds              0
patient_sat_score          0
patient_age                0
patient_waittime           0
patient_length_of_stay     0
Admission_date             0
patient_checkin_date       0
patient_checkout_date      0
comorbidity_index          0
previous_admissions        0
medication_count           0
socioeconomic_status       0
follow_up_scheduled        0
readmission                0
dtype: int64

Peek at the dataset

# checking duplicates

In [124]:
duplicates =data.duplicated().sum()
duplicates

0

In [125]:
data.head(2)

,Unnamed: 0,hospital_name,hospital_id,patient_id,doctor_id,Patient_first_name,Patient_last_name,doctor_name,hospital_ward,patient_gender,...,patient_length_of_stay,Admission_date,patient_checkin_date,patient_checkout_date,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission
0,0,Tokyo Medical University Hospital,8270,62800,2527,Ming,Chen,Dr. Riko Fujimoto,Cardiology,Male,...,15,23-01-2023,25-01-2023,09-02-2023,2,0,5,Medium,1,0
1,1,Tokyo Medical University Hospital,1860,15445,3026,Jie,Nakamura,Dr. Takashi Matsuda,Cardiology,Male,...,14,15-10-2024,16-10-2024,30-10-2024,5,0,2,Low,1,0

In [126]:
data.dtypes

Unnamed: 0                  int64
hospital_name              object
hospital_id                 int64
patient_id                  int64
doctor_id                   int64
Patient_first_name         object
Patient_last_name          object
doctor_name                object
hospital_ward              object
patient_gender             object
patient_race               object
department_referral        object
doctor_specialty           object
patient_assigned_doctor      bool
patient_disease            object
discharge_status           object
time_slot                  object
hospital_beds_available     int64
occupied_beds               int64
patient_sat_score           int64
patient_age                 int64
patient_waittime            int64
patient_length_of_stay      int64
Admission_date             object
patient_checkin_date       object
patient_checkout_date      object
comorbidity_index           int64
previous_admissions         int64
medication_count            int64
socioeconomic_status       object
follow_up_scheduled         int64
readmission                 int64
dtype: object

In [127]:
data['hour'] = pd.to_datetime(data['time_slot'], format='%H:%M').dt.hour

In [128]:
data['Admission_date'] = pd.to_datetime(data['Admission_date'], format='%d-%m-%Y')

In [129]:
print(data.dtypes)

Unnamed: 0                          int64
hospital_name                      object
hospital_id                         int64
patient_id                          int64
doctor_id                           int64
Patient_first_name                 object
Patient_last_name                  object
doctor_name                        object
hospital_ward                      object
patient_gender                     object
patient_race                       object
department_referral                object
doctor_specialty                   object
patient_assigned_doctor              bool
patient_disease                    object
discharge_status                   object
time_slot                          object
hospital_beds_available             int64
occupied_beds                       int64
patient_sat_score                   int64
patient_age                         int64
patient_waittime                    int64
patient_length_of_stay              int64
Admission_date             datetime64[ns]
patient_checkin_date               object
patient_checkout_date              object
comorbidity_index                   int64
previous_admissions                 int64
medication_count                    int64
socioeconomic_status               object
follow_up_scheduled                 int64
readmission                         int64
hour                                int32
dtype: object

In [130]:
unique_hospital_ward = data['hospital_ward'].unique() 
unique_hospital_ward
unique_hospital_ward_count=data['hospital_ward'].value_counts()
unique_hospital_ward_count

hospital_ward
General        3017
Surgery        1580
Pediatrics     1472
Maternity      1460
ICU             969
Cardiology      533
Oncology        489
Neurology       282
Orthopedics     198
Name: count, dtype: int64

In [131]:
Patient_gender = data['patient_gender'].unique()
Patient_gender

array(['Male', 'Female'], dtype=object)

In [132]:
Patient_assgn_doctor = data['patient_assigned_doctor'].value_counts()
Patient_assgn_doctor

patient_assigned_doctor
True     9037
False     963
Name: count, dtype: int64

In [133]:
data.head(1)

,Unnamed: 0,hospital_name,hospital_id,patient_id,doctor_id,Patient_first_name,Patient_last_name,doctor_name,hospital_ward,patient_gender,...,Admission_date,patient_checkin_date,patient_checkout_date,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission,hour
0,0,Tokyo Medical University Hospital,8270,62800,2527,Ming,Chen,Dr. Riko Fujimoto,Cardiology,Male,...,2023-01-23,25-01-2023,09-02-2023,2,0,5,Medium,1,0,17

In [134]:
patient_disease =data['patient_disease'].value_counts()
patient_disease

patient_disease
Hypertension      2021
Diabetes          1550
Heart Disease     1483
Pneumonia         1026
Arthritis         1018
Asthma             991
Cancer             941
Stroke             497
Kidney Disease     473
Name: count, dtype: int64

In [135]:
discharge_status = data['discharge_status'].value_counts()
discharge_status

discharge_status
Recovered      7088
Transferred    1950
Deceased        962
Name: count, dtype: int64

In [136]:
various_department_reffered =data['department_referral'].value_counts()
various_department_reffered

department_referral
Cardiology          2048
General Medicine    1952
Orthopedics         1522
Oncology            1514
Neurology           1504
Gastroenterology    1460
Name: count, dtype: int64

In [137]:
Satisfactory_level = data['patient_sat_score'].value_counts()
Satisfactory_level

patient_sat_score
6     1975
7     1918
5     1486
8     1463
9      910
4      889
10     683
3      442
2      173
1       61
Name: count, dtype: int64

In [138]:
Patient_race = data['patient_race'].value_counts()
Patient_race

patient_race
Japanese       6992
Korean         1008
Chinese         993
Caucasian       519
South Asian     299
Other           189
Name: count, dtype: int64

In [139]:
data.columns

Index(['Unnamed: 0', 'hospital_name', 'hospital_id', 'patient_id', 'doctor_id',
       'Patient_first_name', 'Patient_last_name', 'doctor_name',
       'hospital_ward', 'patient_gender', 'patient_race',
       'department_referral', 'doctor_specialty', 'patient_assigned_doctor',
       'patient_disease', 'discharge_status', 'time_slot',
       'hospital_beds_available', 'occupied_beds', 'patient_sat_score',
       'patient_age', 'patient_waittime', 'patient_length_of_stay',
       'Admission_date', 'patient_checkin_date', 'patient_checkout_date',
       'comorbidity_index', 'previous_admissions', 'medication_count',
       'socioeconomic_status', 'follow_up_scheduled', 'readmission', 'hour'],
      dtype='object')

In [140]:
data.head(1)

,Unnamed: 0,hospital_name,hospital_id,patient_id,doctor_id,Patient_first_name,Patient_last_name,doctor_name,hospital_ward,patient_gender,...,Admission_date,patient_checkin_date,patient_checkout_date,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission,hour
0,0,Tokyo Medical University Hospital,8270,62800,2527,Ming,Chen,Dr. Riko Fujimoto,Cardiology,Male,...,2023-01-23,25-01-2023,09-02-2023,2,0,5,Medium,1,0,17

## Cleaning

In [141]:
# Columns we are dropping intentionally
columns_to_drop = [
    'Unnamed: 0', 'hospital_name', 'hospital_id', 'patient_id', 'doctor_id',
    'Patient_first_name', 'Patient_last_name', 'doctor_name', 'hospital_ward',
    'Admission_date', 'patient_checkin_date', 'patient_checkout_date',
    'hour', 'admission_month','patient_assigned_doctor'
]

# Drop the columns
data_cleaned = data.drop(columns=columns_to_drop, errors='ignore')
data_cleaned

,patient_gender,patient_race,department_referral,doctor_specialty,patient_disease,discharge_status,time_slot,hospital_beds_available,occupied_beds,patient_sat_score,patient_age,patient_waittime,patient_length_of_stay,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission
0,Male,Japanese,Neurology,Pediatrics,Pneumonia,Recovered,17:32,170,110,4,30,42,15,2,0,5,Medium,1,0
1,Male,Japanese,Cardiology,Oncology,Diabetes,Recovered,00:38,198,108,9,71,85,14,5,0,2,Low,1,0
2,Male,Japanese,Cardiology,Orthopedics,Pneumonia,Recovered,20:25,183,128,10,24,88,6,3,2,3,Medium,1,0
3,Male,Japanese,General Medicine,Gastroenterology,Heart Disease,Recovered,20:33,390,243,9,1,54,9,4,3,3,High,1,0
4,Female,Chinese,Cardiology,Cardiology,Hypertension,Recovered,23:52,212,157,9,30,109,10,3,0,3,Low,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,Japanese,Oncology,Gastroenterology,Hypertension,Transferred,03:12,214,180,8,58,58,4,4,0,2,Medium,0,0
9996,Male,Japanese,Orthopedics,Orthopedics,Hypertension,Recovered,05:42,259,193,7,72,83,5,5,2,4,Medium,1,0
9997,Female,Japanese,Cardiology,Pediatrics,Hypertension,Recovered,14:38,329,227,6,39,65,7,2,0,3,Medium,0,1
9998,Male,Japanese,Orthopedics,Orthopedics,Hypertension,Transferred,09:41,237,191,8,32,30,9,4,2,2,Medium,1,1
9999,Female,Korean,Oncology,Cardiology,Diabetes,Transferred,16:18,252,230,4,21,59,3,2,2,6,Low,1,1

In [142]:
data_cleaned.columns

Index(['patient_gender', 'patient_race', 'department_referral',
       'doctor_specialty', 'patient_disease', 'discharge_status', 'time_slot',
       'hospital_beds_available', 'occupied_beds', 'patient_sat_score',
       'patient_age', 'patient_waittime', 'patient_length_of_stay',
       'comorbidity_index', 'previous_admissions', 'medication_count',
       'socioeconomic_status', 'follow_up_scheduled', 'readmission'],
      dtype='object')

In [143]:
categoricl_cols = [ cols for cols in data_cleaned.columns if data_cleaned[cols].dtype =="O"]
print(categoricl_cols)

['patient_gender', 'patient_race', 'department_referral', 'doctor_specialty', 'patient_disease', 'discharge_status', 'time_slot', 'socioeconomic_status']

In [144]:
from sklearn.preprocessing import LabelEncoder
# List of categorical columns
categorical_cols = [
    'patient_gender', 'patient_race', 'department_referral', 'doctor_specialty',
    'patient_disease', 'discharge_status',
    'time_slot', 'socioeconomic_status'
]

for col in categoricl_cols:
    le = LabelEncoder()
    data_cleaned[col] = le.fit_transform(data[col])

data_cleaned['readmission']=le.fit_transform(data_cleaned['readmission'])

readmission_data_tokyo =data_cleaned.to_csv("readmission_tokyo_encoded.csv",index=False)

In [145]:
data_cleaned.head(1)

,patient_gender,patient_race,department_referral,doctor_specialty,patient_disease,discharge_status,time_slot,hospital_beds_available,occupied_beds,patient_sat_score,patient_age,patient_waittime,patient_length_of_stay,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission
0,1,2,3,6,7,1,1049,170,110,4,30,42,15,2,0,5,2,1,0

In [146]:
data_cleaned.columns

Index(['patient_gender', 'patient_race', 'department_referral',
       'doctor_specialty', 'patient_disease', 'discharge_status', 'time_slot',
       'hospital_beds_available', 'occupied_beds', 'patient_sat_score',
       'patient_age', 'patient_waittime', 'patient_length_of_stay',
       'comorbidity_index', 'previous_admissions', 'medication_count',
       'socioeconomic_status', 'follow_up_scheduled', 'readmission'],
      dtype='object')

# feature selection

In [147]:
X = data_cleaned.drop(columns=["readmission"])
y = data_cleaned["readmission"]

In [148]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [149]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [150]:
import numpy as np

# Convert the training and test data to NumPy arrays
X_train_np = np.array(X_train)
X_test_np = np.array(X_test)
y_train_np = np.array(y_train)
y_test_np = np.array(y_test)

# Print shapes to confirm
print(f"Training Data (X_train) Shape: {X_train_np.shape}")
print(f"Test Data (X_test) Shape: {X_test_np.shape}")
print(f"Training Labels (y_train) Shape: {y_train_np.shape}")
print(f"Test Labels (y_test) Shape: {y_test_np.shape}")

Training Data (X_train) Shape: (8000, 18)
Test Data (X_test) Shape: (2000, 18)
Training Labels (y_train) Shape: (8000,)
Test Labels (y_test) Shape: (2000,)

# LABEL ENCODING OTHER HOSPITAL DATA

In [151]:
df =pd.read_csv("London_General_Hospital_Dataset.csv")

In [152]:
df.columns

Index(['patient_gender', 'patient_race', 'department_referral',
       'doctor_specialty', 'patient_disease', 'discharge_status', 'time_slot',
       'hospital_beds_available', 'occupied_beds', 'patient_sat_score',
       'patient_age', 'patient_waittime', 'patient_length_of_stay',
       'comorbidity_index', 'previous_admissions', 'medication_count',
       'socioeconomic_status', 'follow_up_scheduled', 'readmission'],
      dtype='object')

In [153]:
df.head(2)

,patient_gender,patient_race,department_referral,doctor_specialty,patient_disease,discharge_status,time_slot,hospital_beds_available,occupied_beds,patient_sat_score,patient_age,patient_waittime,patient_length_of_stay,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission
0,Female,Mixed,Oncology,Oncology,Diabetes,Deceased,20:23,449,378,78,15,142,10,3,4,2,High,0,0
1,Male,Mixed,General Medicine,Orthopaedics,COPD,Transferred,10:45,386,232,81,33,138,13,3,0,4,High,1,0

In [154]:
cols_to_drop = [
     'hospital_name', 'hospital_id', 'patient_id', 'doctor_id',
    'patient_first_name', 'patient_last_name', 'doctor_name', 'hospital_ward',
    'patient_checkin_date', 'patient_checkout_date',
    'patient_assigned_doctor','Admission_date'
]

# Drop the columns
df_cleaned = df.drop(columns=cols_to_drop, errors='ignore')
df_cleaned

,patient_gender,patient_race,department_referral,doctor_specialty,patient_disease,discharge_status,time_slot,hospital_beds_available,occupied_beds,patient_sat_score,patient_age,patient_waittime,patient_length_of_stay,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission
0,Female,Mixed,Oncology,Oncology,Diabetes,Deceased,20:23,449,378,78,15,142,10,3,4,2,High,0,0
1,Male,Mixed,General Medicine,Orthopaedics,COPD,Transferred,10:45,386,232,81,33,138,13,3,0,4,High,1,0
2,Male,Asian,A&E,General Practice,Diabetes,Recovered,12:36,464,394,79,43,75,7,3,1,4,Middle,1,0
3,Male,Asian,A&E,General Practice,Hypertension,Transferred,09:54,552,426,86,57,160,8,3,0,2,Middle,1,0
4,Female,White,General Medicine,Oncology,Diabetes,Recovered,02:16,376,314,96,75,56,11,5,2,2,Middle,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,Asian,General Medicine,Surgery,Respiratory Disease,Transferred,12:31,530,326,88,77,89,8,2,0,3,Middle,1,0
9996,Female,White,General Medicine,General Practice,Diabetes,Recovered,06:48,200,148,98,60,247,7,4,2,5,Low,0,1
9997,Female,White,A&E,General Practice,Hypertension,Recovered,10:02,329,282,88,67,93,10,2,0,1,Middle,0,0
9998,Male,Asian,Geriatrics,Geriatrics,Hypertension,Recovered,21:34,449,291,100,83,46,9,3,0,1,Middle,1,0
9999,Male,White,Oncology,Oncology,Stroke,Recovered,05:08,464,434,68,62,107,40,5,1,4,High,1,0

In [155]:
df_cleaned.columns

Index(['patient_gender', 'patient_race', 'department_referral',
       'doctor_specialty', 'patient_disease', 'discharge_status', 'time_slot',
       'hospital_beds_available', 'occupied_beds', 'patient_sat_score',
       'patient_age', 'patient_waittime', 'patient_length_of_stay',
       'comorbidity_index', 'previous_admissions', 'medication_count',
       'socioeconomic_status', 'follow_up_scheduled', 'readmission'],
      dtype='object')

In [156]:
categorial_col_dataset2 = [cols for cols in df_cleaned.columns if df_cleaned[cols].dtype=="O"]


categorial_col_dataset2

['patient_gender',
 'patient_race',
 'department_referral',
 'doctor_specialty',
 'patient_disease',
 'discharge_status',
 'time_slot',
 'socioeconomic_status']

In [157]:
from sklearn.preprocessing import LabelEncoder
# List of categorical columns
categorical_cols = [
    'patient_gender', 'patient_race', 'department_referral', 'doctor_specialty',
    'patient_disease', 'discharge_status',
    'time_slot', 'socioeconomic_status'
]

for col in categoricl_cols:
    le = LabelEncoder()
    df_cleaned[col] = le.fit_transform(df[col])

df_cleaned['readmission']=le.fit_transform(df_cleaned['readmission'])

readmission_data_London =df_cleaned.to_csv("readmission_London_encoded.csv",index=False)

In [158]:
df_cleaned.head(1)

,patient_gender,patient_race,department_referral,doctor_specialty,patient_disease,discharge_status,time_slot,hospital_beds_available,occupied_beds,patient_sat_score,patient_age,patient_waittime,patient_length_of_stay,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission
0,0,2,6,5,3,0,1223,449,378,78,15,142,10,3,4,2,0,0,0

In [159]:
X = df_cleaned.drop(columns=["readmission"])
y = df_cleaned["readmission"]

In [160]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [161]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [162]:
import numpy as np

# Convert the training and test data to NumPy arrays
X_train_np = np.array(X_train)
X_test_np = np.array(X_test)
y_train_np = np.array(y_train)
y_test_np = np.array(y_test)

# Print shapes to confirm
print(f"Training Data (X_train) Shape: {X_train_np.shape}")
print(f"Test Data (X_test) Shape: {X_test_np.shape}")
print(f"Training Labels (y_train) Shape: {y_train_np.shape}")
print(f"Test Labels (y_test) Shape: {y_test_np.shape}")

Training Data (X_train) Shape: (8000, 18)
Test Data (X_test) Shape: (2000, 18)
Training Labels (y_train) Shape: (8000,)
Test Labels (y_test) Shape: (2000,)

LABEL ENCODING JOHN HOSPITAL

In [3]:
df =pd.read_csv("Johns_Hospital_Data.csv")

In [4]:
df.columns

Index(['patient_gender', 'patient_race', 'department_referral',
       'doctor_specialty', 'patient_disease', 'discharge_status', 'time_slot',
       'hospital_beds_available', 'occupied_beds', 'patient_sat_score',
       'patient_age', 'patient_waittime', 'patient_length_of_stay',
       'comorbidity_index', 'previous_admissions', 'medication_count',
       'socioeconomic_status', 'follow_up_scheduled', 'readmission'],
      dtype='object')

In [5]:
df.head(2)

,patient_gender,patient_race,department_referral,doctor_specialty,patient_disease,discharge_status,time_slot,hospital_beds_available,occupied_beds,patient_sat_score,patient_age,patient_waittime,patient_length_of_stay,comorbidity_index,previous_admissions,medication_count,socioeconomic_status,follow_up_scheduled,readmission
0,Female,Asian,Urology or Nephrology,Rheumatology,Anxiety Disorders,Deceased,20:23:00,260,90,62,48,120,6,6,1,4,high,1,1
1,Male,Black,Neurology,Pulmonology or Allergy and Immunology,Urinary Tract Infection (UTI),Deceased,10:45:00,250,90,80,40,60,2,2,2,2,low,1,1